services:
  bitmagnet:
    container_name: bitmagnet
    build:
      context: .
      dockerfile: Dockerfile.scratch
      args:
        GIT_TAG: local
    image: bitmagnet:local
    volumes:
      - ./config:/root/.config/bitmagnet
      - ./data/bitmagnet:/root/.local/share/bitmagnet
    restart: unless-stopped
    environment:
      - HOME=/root
      - XDG_CONFIG_HOME=/root/.config
      - XDG_DATA_HOME=/root/.local/share
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - TMDB_ENABLED=false
    ports:
      - "3333:3333"
      - "3334:3334/tcp"
      - "3334:3334/udp"
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      # Remove the next line if you do not want the crawler to populate the index.
      - --keys=dht_crawler

  postgres:
    image: postgres:16-alpine
    container_name: bitmagnet-postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    shm_size: 1g
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bitmagnet
      - PGUSER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      start_period: 20s
